### ISSUE TITLE
Issue - Missing/ None (Mono Script)

### ISSUE THREAD

**Issue by GoetteVictoria** [5ahmnm2122/04CandyCatcher-sfeld#1]
> None (Mono Script) --> auf dem Cm vcam1 Object in der MainScene, EndScene, IntroScene

> None (Mono Script) --> auf dem Main Camera Object in der MainScene, End Scene, IntroScene

**Comment by feldbacherSimone** [comment]
Da muss noch das Cinemachine Package installiert werden, hab ich vergessen ins Reamed zu Schreiben, jetzt ist es drinnen
